name: Main branch protection

run-name: "Main branch protection"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/callable-build.yaml

  test:
    uses: ./.github/workflows/callable-test.yaml
