name: Pull request validation

run-name: "Pull request validation: #${{ github.event.pull_request.number }}"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: "pull-request-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  go:
    name: Golang
    uses: ./.github/workflows/callable-go.yaml

  py:
    name: Python
    uses: ./.github/workflows/callable-py.yaml

  image:
    name: Image
    uses: ./.github/workflows/callable-image.yaml
    with:
      version: "${{ github.event.pull_request.number }}"
      push: false
