name: Pull request validation

run-name: "Pull request validation: #${{ github.event.pull_request.number }}"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: "pull-request-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/callable-build.yaml

  test:
    uses: ./.github/workflows/callable-test.yaml
